using System;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace MB2Mod.NPCMasterTrainer
{
    internal class ScriptingInterfaceOfIInput
    {
        [MethodImpl(MethodImplOptions.NoInlining)]
        public string GetClipboardText()
        {
            var text = Utils.Clipboard.GetTextOrEmpty();
            if (Utils.Config.Instance.HasWin32Console())
            {
                Console.WriteLine($"GetClipboardText: {text}");
            }
            return text;
        }

        public static void FixGetClipboardText()
        {
            try
            {
                var destination = typeof(ScriptingInterfaceOfIInput).GetMethod("GetClipboardText", BindingFlags.Instance | BindingFlags.Public);
                var assembly = Utils.CurrentAppDomain.Values.FirstOrDefault(x => x.GetName().Name == "TaleWorlds.Engine.AutoGenerated");
                if (assembly == default) return;
                var type = assembly.GetType("ManagedCallbacks.ScriptingInterfaceOfIInput");
                if (type == default) return;
                var source = type.GetMethod("GetClipboardText", BindingFlags.Instance | BindingFlags.Public);
                if (source == default) return;
                Utils.Hook.ReplaceMethod(source, destination);
                if (Utils.Config.Instance.HasWin32Console())
                {
                    Console.WriteLine("FixGetClipboardText Success.");
                }
            }
            catch (Exception e)
            {
                Utils.DisplayMessage(e);
            }
        }
    }
}
